### PR TITLE
#8 update readme to suggest open push event by default

### PR DESCRIPTION
**Pull request by shenxianpeng**

### CODE REVIEW

**Review by 2bndy5 — COMMENTED** [review]
I've already tried this in my fork during testing #4 . Push events currently fail because the git API call is specifically tailored to PRs. The logs currently indicate this failure by printing [`Files = null/files`](https://github.com/2bndy5/cpp-linter-action/runs/3360291332?check_suite_focus=true#step:4:8)

**Review by 2bndy5 — CHANGES_REQUESTED** [review]
I'll approve this after #14 is merged into this branch

**Comment by shenxianpeng** [comment]
Merge this one as #14 is merged.

**Review by 2bndy5 — APPROVED** [review]
I had to resolve some conflicts in the merge of #14 and then test the resolutions on this branch. Everything looks good.

**Comment by shenxianpeng** [comment]
Great, merged!

**Pull request merged**
