### PR TITLE
add file-annotations option

### PR DESCRIPTION
**Pull request by 2bndy5**
Add an option to enable/disable the use of file annotations. This includes changes to the README, ~so there might be a conflict with #57.~

### CODE REVIEW

**Comment by 2bndy5** [comment]
I tested this option on the test repo. In a matrix that runs the action for all versions of clang-tools, only annotations (& thread comments) were enabled for v12. It worked as expected.

**Review by shenxianpeng — APPROVED** [review]

**Comment by shenxianpeng** [comment]
Do you think we need to update the YAML example in README to help users avoid adding duplicate annotaions?

**Comment by 2bndy5** [comment]
Well, following the discussion in #58, it seems that there are several ways to trigger duplicate annotations.
I think I'd propose the example snippets demonstrate using specific event types rather than using this new option.
```yml
on:
  pull_request:
    types: [opened, reopened]  # let PR-synchronize events be handled by push events
  push:
```

The current examples use `paths-ignore` which is very specific to this repo:
```yml
push:
    paths-ignore: "docs/**"
  pull_request:
    paths-ignore: "docs/**"
```

**Comment by shenxianpeng** [comment]
I like your propose 👍

**Comment by 2bndy5** [comment]
I accidentally rebased on an older commit in master, so the commits in #57 now show in this branch's history. Please squash and merge this when ready.

**Comment by shenxianpeng** [comment]
OK. do you know why the PR action is queued https://github.com/shenxianpeng/test-cpp-linter-action/actions/runs/2236867491
is it related to the change below?

```
on:
  pull_request:
    types: [opened, reopened]  # let PR-synchronize events be handled by push events
  push:
```

**Comment by 2bndy5** [comment]
I have no idea. I tried canceling the run (hoping to manually re-start it), but I got a error message from github saying "failed to cancel the workflow run". It doesn't seem to be related.

Sometimes, I see a runner in queue when waiting for a github hosted VM to become available, but it doesn't even say that much. 🤷🏼‍♂️

**Comment by 2bndy5** [comment]
It looks like a github problem. I see you closed and re-opened the PR which seemed to have expected results.

**Comment by shenxianpeng** [comment]
OK, I'm going to squash and merge.

**Pull request merged**
