### PR TITLE
[feat] Add ability to specify the compilation database

### PR DESCRIPTION
**Pull request by DingXuefeng**
Add ability to specify the compilation database through `clang-format -p xxx.json` machinery, so that the head files can be included properly.

### CODE REVIEW

**Comment by 2bndy5** [comment]
closes #41

**Comment by 2bndy5** [comment]
I've been testing this. It works locally, but I get an error on the test repo using a generated database from CMake on the GitHub runner.
```
  INFO:CPP Linter:Running "clang-tidy-10 -checks=boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-* --export-fixes=clang_tidy_output.yml -p build src/demo.cpp"
  DEBUG:CPP Linter:Output from clang-tidy:
  
  WARNING:CPP Linter:clang-tidy-10 raised the following error(s):
  LLVM ERROR: Cannot chdir into "/home/runner/work/test-cpp-linter-action/test-cpp-linter-action/build"!
```
I'm still investigating if its just a workflow problem. The path seems correct though (duplicated folder names are from git checkout).

It would seem different version's of clang-tidy output something different:
```
  WARNING:CPP Linter:clang-tidy-12 raised the following error(s):
  LLVM ERROR: Cannot chdir into "/home/runner/work/test-cpp-linter-action/test-cpp-linter-action/build"!
  PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
  Stack dump:
  0.	Program arguments: clang-tidy-12 -checks=boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-* --export-fixes=clang_tidy_output.yml -p=build src/demo.hpp
  Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
  /lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamEi+0x23)[0x7f54b9db8ef3]
  /lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0x50)[0x7f54b9db7210]
  /lib/x86_64-linux-gnu/libLLVM-12.so.1(+0xbd955f)[0x7f54b9db955f]
  /lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f54c15ef3c0]
  /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f54b8ce618b]
  /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f54b8cc5859]
  /lib/x86_64-linux-gnu/libLLVM-12.so.1(+0xb34209)[0x7f54b9d14209]
  /lib/x86_64-linux-gnu/libclang-cpp.so.12(_ZN5clang7tooling9ClangTool3runEPNS0_10ToolActionE+0x10cb)[0x7f54c09d704b]
  clang-tidy-12[0x87c377]
  clang-tidy-12[0x45833d]
  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f54b8cc70b3]
  clang-tidy-12[0x45612e]
```

I also can't seem to get clang-tidy-13 to work, but again, that's not a problem with these changes.

**Comment by 2bndy5** [comment]
I have a feeling it may have something to do with the docker image's access to runner's File System.

**Review by 2bndy5 — APPROVED** [review]
I think its ok to merge this, but I'd really like to get the `database` option to work when specified. Its causing clang-tidy to crash which we have to ignore because of multiple files. To be clear, it does work as a python package executable:

```yml
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install clang-tools
        run : sudo apt-get update && sudo apt-get install clang-tidy-${{ matrix.clang-version }} clang-format-${{ matrix.clang-version }}
      - name: Install linter package
        run: python -m pip install git+https://github.com/shenxianpeng/cpp-linter-action/@refs/pull/42/head
      - name: Generate  compiler database  
        run: mkdir build && cmake -Bbuild src
      - name: run linter as package
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cpp_linter -s=file -i=build -p=build -V=${{ matrix.clang-version }}
```
But it doesn't work using:
```yml
    steps:
      - uses: actions/checkout@v2
      - name: Generate compilation database
        run: mkdir build && cmake -Bbuild src
      - name: run linter as action
        uses: shenxianpeng/cpp-linter-action@refs/pull/42/head
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          ignore: build
          database: build
          version: ${{ matrix.clang-version }}
```
I think its a File system access thing.

**Comment by DingXuefeng** [comment]
> I think its ok to merge this, but I'd really like to get the `database` option to work when specified. Its causing clang-tidy to crash which we have to ignore because of multiple files. To be clear, it does work as a python package executable:
> 
> ```yaml
>     steps:
>       - uses: actions/checkout@v2
>       - uses: actions/setup-python@v1
>       - name: Install clang-tools
>         run : sudo apt-get update && sudo apt-get install clang-tidy-${{ matrix.clang-version }} clang-format-${{ matrix.clang-version }}
>       - name: Install linter package
>         run: python -m pip install git+https://github.com/shenxianpeng/cpp-linter-action/@refs/pull/42/head
>       - name: Generate  compiler database  
>         run: mkdir build && cmake -Bbuild src
>       - name: run linter as package
>         id: linter
>         env:
>           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>         run: cpp_linter -s=file -i=build -p=build -V=${{ matrix.clang-version }}
> ```
> 
> But it doesn't work using:
> 
> ```yaml
>     steps:
>       - uses: actions/checkout@v2
>       - name: Generate compilation database
>         run: mkdir build && cmake -Bbuild src
>       - name: run linter as action
>         uses: shenxianpeng/cpp-linter-action@refs/pull/42/head
>         id: linter
>         env:
>           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>         with:
>           style: file
>           ignore: build
>           database: build
>           version: ${{ matrix.clang-version }}
> ```
> 
> I think its a File system access thing.

I cannot reproduce the bug you mentioned. See [a github run action result](https://github.com/DingXuefeng/program-analysis/actions/runs/2031969114). 

If you believe it's a bug, you can open another issue and provide a minimal reproducible example.

**Comment by 2bndy5** [comment]
@DingXuefeng [Your example workflow](https://github.com/DingXuefeng/program-analysis/blob/b165388d1889a31857079d7fb3d4c6e628b5d9a1/.github/workflows/cpp-linter.yml) doesn't actually use a generated build/compile_commads.json.
```yml
      - name: Generate compilation database
        run: mkdir build && cmake -Bbuild . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
```
What happens when there is a database that exists?

**Review by shenxianpeng — APPROVED** [review]

**Comment by DingXuefeng** [comment]
Hi, I can reproduce

> 

Hi, I can reproduce what you see now.

The problem is due to the fact that `compile_commands.json` has absolute command built-in, while in the docker they are [mapped to `/github/workspace` folder](https://github.community/t/how-can-i-access-the-current-repo-context-and-files-from-a-docker-container-action/17711). I have no good solution now. Maybe `ln -sf $GITHUB_WORKSPACE /github/workspace`.

Wondering how other github actions handled this.

**Comment by 2bndy5** [comment]
>Wondering how other github actions handled this.

We can use the [built-in env var: `GITHUB_WORKSPACE`](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables). I've already push that change with consideration that it isn't needed locally (executed when not on a runner).

**Review by 2bndy5 — APPROVED** [review]
Great work @DingXuefeng ! I changed the fix to use the `RUNNER_WOKSPACE` env var. Tested it again, and everything works as expected.

**Comment by shenxianpeng** [comment]
Well done. thank you both!

**Pull request merged**
