### PR TITLE
Push capable

### LINKED ISSUE #6: Prevent action downloading files after GH checkout action
If you require the user's repos uses GH's actions/checkout prior to the cpp-lint action, then all files are already there in a folder designated by the environment variable `$GITHUB_WORKSPACE`.

The JSON that the bash script is getting the list of download URLs can instead be used to get the relative path of files. This way, you'd only have to prefix the filenames with `$GITHUB_WORKSPACE` when passing them to clang-* tools.

### LINKED ISSUE #8: add compatibility for push events
It would be more useful if a user is notified by this action (before opening a PR) that a file from a commit needs formatting. Users workflows can clarify what [events to trigger on](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on).

### PR DESCRIPTION
**Pull request by 2bndy5**
Properly resolves #8 
Also resolves #6 

- source files are only downloaded if the action (run in the repo's root directory) cannot find the changed file.
- added a new user input called `repo-root` that allows user to specify a relative path. This makes the action change its working directory to whatever folder the user `git checkout` their source code to.
   - testing has shown that using the actions/checkout action from GH yields faster results when this action doesn't need to download the source files.
- bot comments are now augmented so that they include output from clang-tidy and clang-format.
   Observe https://github.com/2bndy5/cpp-linter-action/commit/f26cabc5ae6529365bbbd51ab91c23abe12ce664#commitcomment-55219273 as an example. Incidentally, that commit comment is added to this PR's comments.
   - I did this because it seemed like a bug in the original script was preventing both outputs from showing in the bot's posted comment.
- added a new user input called `tidy-checks` to allow specifying a different set of checks passed to clang-tidy. By setting this input to `''`, this allows users to make clang-tidy use either the default checks or only whatever checks are specified in an optionally accompanied .clang-tidy config file.
- the READEME updates in this PR do not include the README changes from #9. So, that PR can be merged after this gets merged into it.
- For the benefit of prospecting contributors, I've segregated the `run_checks.sh` script into byte-sized functions and added comments for anything that isn't completely obvious.
   - There's even some instructions at the bottom to help develop the script locally on bash terminals without needing docker installed. These instructions are likely to change a bit as we move to solve shenxianpeng/clang-tools#1
- added a .gitattributes file to ensure the bash script file consistently uses Unix LF instead of letting windows-based developers contribute illegal CRLF into the bash script.
- Docker file uses `FROM shenxianpeng/clang-tool:10` for behavior consistent with older releases of this action. This too will change as we move to solve shenxianpeng/clang-tools#1

### CODE REVIEW

**Comment by shenxianpeng** [comment]
Your changes look so awesome, I can’t wait to merge them.

**Comment by 2bndy5** [comment]
Please hold. I'm integratinmg the new docker image... (& adding the corresponding user input)

**Comment by 2bndy5** [comment]
Ok, the new image checks out. It did seem to take longer to set up, but its still about 1.5 minutes faster than the other clang-tidy actions on the GH marketplace that also support all available versions.

I also added (un-commented) the user option to specify a version in the action.yml

**Review by shenxianpeng — APPROVED** [review]

**Comment by shenxianpeng** [comment]
We are pretty fast 😃 see from actions: now it takes `2m 17s` than before `55s`.

**Comment by 2bndy5** [comment]
yep that one other action that uses primarily python to create automatic reviews takes about 3m 35s to build the action's image and then about another 1m 30s to execute the action.

**Pull request merged**
