### PR TITLE
#15 update README.md and action.yml

### PR DESCRIPTION
**Pull request by shenxianpeng**
Update README.md and add result.png to demo folder.

### CODE REVIEW

**Comment by shenxianpeng** [comment]
> Before you make a new release it may be prudent to delete any previously posted comments (made by the bot) when posting new comments to the same thread.

Sorry, I don't get your point, can you explain more?
I'm not an English native speaker, could you help to review and modify if need? 
Thank you.

**Comment by 2bndy5** [comment]
Imagine a PR is opened and the source file(s) invoke a bot comment from this action. Any successive commits to the same PR will only add more bot comments to that PR not replace or remove any outdated bot comments.

There is a way to update a comment via the REST API.

**Comment by 2bndy5** [comment]
I think the repo's description should be updated also. This is to make it stick out less like a duplicate and more like an improved fork
image
vs the older
image

This can be only done by you in the repo's sidebar's settings
image

**Comment by shenxianpeng** [comment]
👍 I will update in one hour when I back from lunch/dinner.

**Comment by shenxianpeng** [comment]
Or change the repo's description to "GitHub Action for Linting C/C++ code as part of your workflows!". your thoughts?

**Comment by shenxianpeng** [comment]
I think after this release, the name of this GitHub app should be changed to "C/C++ Lint Action"

**Comment by 2bndy5** [comment]
Best to use the words (in the description)
- "improved" (or something similar - maybe "evolved")
- "push" (non-negotiable)
- "pull_request" (maybe implied but could be informative)

I think the name (if changed) would need to be done prior to release. See the [GH docs about action.yml metadata](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#name). IMHO, I like the idea of renaming the action also (I also like your suggested idea).

**Comment by shenxianpeng** [comment]
"IMPROVED C/C++ Lint Action: Automatically checks pull/pull request changes with clang-tidy, clang-format, and posts the comment with result.", like this?

**Comment by 2bndy5** [comment]
How do you like this?

Improved C/C++ Lint Action: Automatically checks push & pull request changes with clang-tidy & clang-format, then posts a comment with faulty results

**Comment by shenxianpeng** [comment]
>Imagine a PR is opened and the source file(s) invoke a bot comment from this action. Any successive commits to the same PR >will only add more bot comments to that PR not replace or remove any outdated bot comments.

>There is a way to update a comment via the REST API.

Yes, this is a problem. but if only has `opened` type event of pull_request, new commits include new source file(s) changes will not have bot comments. does REST API can deal with this

**Comment by 2bndy5** [comment]
That only avoids duplicate triggered runs for 1 commit. I want to avoid a scenario like what I see in one of [my testing PRs](https://github.com/2bndy5/cpp-linter-action/pull/2) Notice the multiple comments made.

**Comment by shenxianpeng** [comment]
Maybe we can create another ticket to track avoid duplicate comments issue rather than limit pull_request type to `opened`

For this version, I guess it's ready to release. assign to you for review.

**Review by 2bndy5 — APPROVED** [review]
ok. I guess users will have to manage/edit/delete comments at their behest (for now).

I often forget that it is best to release often rather than release huge number of changes seldomly.

**Comment by shenxianpeng** [comment]
It seems there is no way to see how many users are using this app. I guess very little. 
This version is much better than before, and we should let them see it as soon as possible.

**Comment by 2bndy5** [comment]
Technically [the marketplace's page for this action](https://github.com/marketplace/actions/c-c-code-linter-clang-tidy-and-clang-format) is up-to-date with the repo's master branch (despite if a release has happened or not).

**Comment by shenxianpeng** [comment]
You're right. the release looks only affect the app's name and description.

**Pull request merged**
